name: ETF Strategy Auto Run

on:
  schedule:
    # IST 10:00 AM = UTC 04:30
    - cron: "30 4 * * 1-5"

    # IST 02:55 PM = UTC 09:25
    - cron: "25 9 * * 1-5"

  workflow_dispatch:

jobs:
  run-etf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETF Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TZ: Asia/Kolkata
        run: python ETF_KI_DUKAN.py
